// components/AccessGate.tsx

import React, { useState } from 'react';
import { Button, Input, Label, Card, Tabs, TabsList, TabsTrigger } from './ui-components';
import { ShieldCheck, Mail, Lock, ArrowRight, Smartphone, Key, Loader2, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { SupabaseService } from '../services/supabase';

interface AccessGateProps {
    documentTitle: string;
    onAccessGranted: (identifier: string) => void;
}

export const AccessGate: React.FC<AccessGateProps> = ({ documentTitle, onAccessGranted }) => {
    const [step, setStep] = useState<'method' | 'otp'>('method');
    const [method, setMethod] = useState<'email' | 'phone'>('email');
    const [identifier, setIdentifier] = useState('');
    const [otp, setOtp] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Mock ID for current document in context context (In real app, passed via props)
    const docId = 'doc_session'; 

    const handleRequestCode = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        if(!identifier) { setError("Please enter a valid email or phone number"); return; }
        
        setIsLoading(true);
        try {
            await SupabaseService.requestAccessCode(docId, identifier);
            setStep('otp');
        } catch (e) {
            setError("Failed to send code. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleVerifyCode = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);
        setError(null);
        
        try {
            const isValid = await SupabaseService.verifyAccessCode(docId, identifier, otp);
            if (isValid) {
                onAccessGranted(identifier);
            } else {
                setError("Invalid Code. Please check your messages.");
            }
        } catch (e) {
            setError("Verification failed.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-zinc-50 dark:bg-zinc-950 p-4 bg-grid-pattern">
            <Card className="w-full max-w-md p-8 space-y-8 shadow-2xl border-2 border-black dark:border-white">
                <div className="text-center space-y-4">
                    <div className="w-16 h-16 bg-black text-white dark:bg-white dark:text-black rounded-none flex items-center justify-center mx-auto mb-4 border-2 border-transparent shadow-sharp">
                        <ShieldCheck size={32} />
                    </div>
                    <div className="space-y-1">
                        <h1 className="text-xl font-black tracking-tight font-mono uppercase">Secure Gateway</h1>
                        <p className="text-muted-foreground text-xs font-mono uppercase tracking-widest">
                            2-Factor Authentication Required
                        </p>
                    </div>
                </div>

                <div className="bg-muted/10 p-4 border-l-4 border-primary text-sm">
                    <p className="mb-1 text-xs font-bold uppercase text-primary">Target Document:</p>
                    <p className="font-semibold">{documentTitle}</p>
                </div>

                {step === 'method' ? (
                    <form onSubmit={handleRequestCode} className="space-y-6 animate-in slide-in-from-right duration-300">
                        <Tabs defaultValue="email" onValueChange={(v) => { setMethod(v as any); setIdentifier(''); setError(null); }}>
                            <TabsList className="grid grid-cols-2 mb-4 bg-muted/20">
                                <TabsTrigger value="email" className="rounded-none data-[state=active]:bg-black data-[state=active]:text-white"><Mail size={14} className="mr-2"/> Email</TabsTrigger>
                                <TabsTrigger value="phone" className="rounded-none data-[state=active]:bg-black data-[state=active]:text-white"><Smartphone size={14} className="mr-2"/> SMS</TabsTrigger>
                            </TabsList>
                        </Tabs>

                        <div className="space-y-2">
                            <Label>{method === 'email' ? 'Email Address' : 'Mobile Number'}</Label>
                            <div className="relative">
                                {method === 'email' ? (
                                    <Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                                ) : (
                                    <Smartphone className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                                )}
                                <Input 
                                    type={method === 'email' ? "email" : "tel"}
                                    placeholder={method === 'email' ? "name@company.com" : "+1 555 000 0000"} 
                                    className="pl-10 h-11" 
                                    required 
                                    value={identifier}
                                    onChange={e => setIdentifier(e.target.value)}
                                    autoFocus
                                />
                            </div>
                        </div>

                        {error && (
                            <div className="bg-red-50 text-red-600 p-2 text-xs flex items-center gap-2 border border-red-200">
                                <AlertTriangle size={14} /> {error}
                            </div>
                        )}

                        <Button className="w-full h-11" disabled={isLoading}>
                            {isLoading ? <Loader2 className="animate-spin" /> : 'Send Verification Code'}
                        </Button>
                    </form>
                ) : (
                    <form onSubmit={handleVerifyCode} className="space-y-6 animate-in slide-in-from-right duration-300">
                        <div className="space-y-2 text-center">
                            <Label className="text-center block mb-4">Enter 6-Digit Code</Label>
                            <div className="flex justify-center">
                                <Input 
                                    placeholder="000000" 
                                    className="h-16 w-48 tracking-[0.5em] font-mono text-center text-2xl border-black dark:border-white" 
                                    required 
                                    maxLength={6}
                                    value={otp}
                                    onChange={e => setOtp(e.target.value.replace(/\D/g, ''))}
                                    autoFocus
                                />
                            </div>
                            <p className="text-[10px] text-muted-foreground text-center mt-2">
                                Sent to <span className="font-bold text-foreground">{identifier}</span>
                            </p>
                            <p className="text-[9px] text-primary italic">(Check console for code in demo mode)</p>
                        </div>

                        {error && (
                            <div className="bg-red-50 text-red-600 p-2 text-xs flex items-center gap-2 border border-red-200 justify-center">
                                <AlertTriangle size={14} /> {error}
                            </div>
                        )}

                        <Button className="w-full h-11" disabled={isLoading}>
                            {isLoading ? 'Verifying...' : 'Access Document'} <ArrowRight size={16} className="ml-2" />
                        </Button>
                        <button type="button" onClick={() => { setStep('method'); setOtp(''); setError(null); }} className="text-xs text-center w-full text-muted-foreground hover:underline">
                            Change {method === 'email' ? 'Email' : 'Number'}
                        </button>
                    </form>
                )}
                
                <div className="pt-6 border-t border-dashed border-black/10 text-center dark:border-zinc-800">
                     <p className="text-[10px] text-muted-foreground uppercase tracking-widest flex items-center justify-center gap-2">
                         <Lock size={10} /> 256-Bit Encrypted Session
                     </p>
                </div>
            </Card>
        </div>
    );
};

// src/lib/components/AccessGate.svelte
<script lang="ts">
	import { Button, Input, Label, Card } from '$lib/components/ui';
	import { ShieldCheck, Mail, Lock, ArrowRight } from 'lucide-svelte';

	interface AccessGateProps {
		documentTitle: string;
		onAccessGranted: (email: string) => void;
	}

	let { documentTitle, onAccessGranted }: AccessGateProps = $props();

	let step = $state<'email' | 'otp'>('email');
	let email = $state('');
	let otp = $state('');
	let isLoading = $state(false);

	function handleEmailSubmit(e: Event) {
		e.preventDefault();
		isLoading = true;
		// Simulate API call to send OTP
		setTimeout(() => {
			isLoading = false;
			step = 'otp';
		}, 1500);
	}

	function handleOtpSubmit(e: Event) {
		e.preventDefault();
		isLoading = true;
		// Simulate OTP verification
		setTimeout(() => {
			if (otp === '123456') {
				// Mock OTP
				isLoading = false;
				onAccessGranted(email);
			} else {
				alert('Invalid Code (Try 123456)');
				isLoading = false;
			}
		}, 1500);
	}
</script>

<div
	class="flex min-h-screen items-center justify-center bg-zinc-50 p-4 dark:bg-zinc-950"
>
	<Card class="w-full max-w-md space-y-8 p-8 shadow-2xl dark:border-zinc-800">
		<div class="space-y-2 text-center">
			<div
				class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary/10 text-primary"
			>
				<ShieldCheck size={32} />
			</div>
			<h1 class="text-2xl font-bold tracking-tight">Secure Access</h1>
			<p class="text-sm text-muted-foreground">
				You have been invited to view and sign <br />
				<span class="font-semibold text-foreground">{documentTitle}</span>
			</p>
		</div>

		{#if step === 'email'}
			<form
				onsubmit={handleEmailSubmit}
				class="animate-in slide-in-from-right duration-300 space-y-4"
			>
				<div class="space-y-2">
					<Label>Email Address</Label>
					<div class="relative">
						<div class="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground">
							<Mail size={16} />
						</div>
						<Input
							type="email"
							placeholder="name@company.com"
							class="pl-9"
							required
							bind:value={email}
						/>
					</div>
				</div>
				<Button class="w-full" disabled={isLoading}>
					{isLoading ? 'Sending Code...' : 'Send Verification Code'}
				</Button>
			</form>
		{:else}
			<form
				onsubmit={handleOtpSubmit}
				class="animate-in slide-in-from-right duration-300 space-y-4"
			>
				<div class="space-y-2">
					<Label>Verification Code</Label>
					<div class="relative">
						<div class="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground">
							<Lock size={16} />
						</div>
						<Input
							placeholder="123456"
							class="pl-9 text-center font-mono text-lg tracking-widest"
							required
							maxlength={6}
							bind:value={otp}
						/>
					</div>
					<p class="text-center text-[10px] text-muted-foreground">
						Check your email for the code.
					</p>
				</div>
				<Button class="w-full" disabled={isLoading}>
					{isLoading ? 'Verifying...' : 'Access Document'}
					<ArrowRight size={16} class="ml-2" />
				</Button>
				<button
					type="button"
					onclick={() => (step = 'email')}
					class="w-full text-center text-xs text-muted-foreground hover:underline"
				>
					Change Email
				</button>
			</form>
		{/if}

		<div class="border-t pt-6 text-center dark:border-zinc-800">
			<p
				class="flex items-center justify-center gap-2 text-[10px] uppercase tracking-widest text-muted-foreground"
			>
				<Lock size={10} /> End-to-End Encrypted
			</p>
		</div>
	</Card>
</div>
