// src/components/editor/Toolbox.tsx
'use client';

import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { BlockType } from '@/lib/schemas/blocks';
import {
  Type,
  TextCursor,
  Hash,
  Mail,
  Calendar,
  PenLine,
  Image,
  FileUp,
  Code,
  Calculator,
  CreditCard,
  Video,
  DollarSign,
  Columns,
  GitBranch,
  Repeat,
  CheckSquare,
  Circle,
  List,
} from 'lucide-react';

interface ToolboxItem {
  type: BlockType;
  label: string;
  icon: React.ReactNode;
  category: 'input' | 'content' | 'logic' | 'media';
}

const toolboxItems: ToolboxItem[] = [
  // Input Category
  { type: BlockType.INPUT, label: 'Text Input', icon: <TextCursor size={16} />, category: 'input' },
  { type: BlockType.LONG_TEXT, label: 'Long Text', icon: <Type size={16} />, category: 'input' },
  { type: BlockType.NUMBER, label: 'Number', icon: <Hash size={16} />, category: 'input' },
  { type: BlockType.EMAIL, label: 'Email', icon: <Mail size={16} />, category: 'input' },
  { type: BlockType.DATE, label: 'Date', icon: <Calendar size={16} />, category: 'input' },
  { type: BlockType.SELECT, label: 'Select', icon: <List size={16} />, category: 'input' },
  { type: BlockType.RADIO, label: 'Radio', icon: <Circle size={16} />, category: 'input' },
  
  // Media Category
  { type: BlockType.IMAGE, label: 'Image', icon: <Image size={16} />, category: 'media' },
  { type: BlockType.VIDEO, label: 'Video', icon: <Video size={16} />, category: 'media' },
  { type: BlockType.FILE_UPLOAD, label: 'File Upload', icon: <FileUp size={16} />, category: 'media' },
  { type: BlockType.PAYMENT, label: 'Payment', icon: <CreditCard size={16} />, category: 'media' },
  { type: BlockType.CURRENCY, label: 'Currency', icon: <DollarSign size={16} />, category: 'media' },
];

interface ToolboxProps {
  onAddBlock: (type: BlockType) => void;
}

export const Toolbox = ({ onAddBlock }: ToolboxProps) => {
  const handleDragStart = (e: React.DragEvent, type: BlockType) => {
    e.dataTransfer.setData('application/hyprdoc-block', type);
    e.dataTransfer.effectAllowed = 'copy';
  };

  const renderToolboxItem = (item: ToolboxItem) => (
    <div
      key={item.type}
      draggable
      onDragStart={(e) => handleDragStart(e, item.type)}
      onClick={() => onAddBlock(item.type)}
      className="flex items-center gap-3 p-3 border-2 border-zinc-800 hover:border-amber-500 hover:bg-zinc-900 cursor-grab active:cursor-grabbing transition-colors group"
    >
      <div className="text-zinc-500 group-hover:text-amber-500 transition-colors">
        {item.icon}
      </div>
      <span className="text-sm font-mono text-zinc-300 group-hover:text-zinc-100">
        {item.label}
      </span>
    </div>
  );

  const inputBlocks = toolboxItems.filter(item => item.category === 'input');
  const contentBlocks = toolboxItems.filter(item => item.category === 'content');
  const logicBlocks = toolboxItems.filter(item => item.category === 'logic');
  const mediaBlocks = toolboxItems.filter(item => item.category === 'media');

  return (
    <div className="w-72 border-r-2 border-zinc-800 bg-zinc-950 flex flex-col h-full">
      <div className="p-5 border-b-2 border-zinc-800 h-16 flex items-center justify-between">
        <span className="font-black font-mono text-sm tracking-widest uppercase text-zinc-200">
          Components
        </span>
        <Badge variant="outline" className="text-[10px] font-mono">
          {toolboxItems.length}
        </Badge>
      </div>

      <Tabs defaultValue="input" className="flex-1 flex flex-col">
        <TabsList className="w-full justify-start rounded-none border-b-2 border-zinc-800 bg-transparent p-0 h-auto">
          <TabsTrigger value="input" className="rounded-none data-[state=active]:border-b-2 data-[state=active]:border-amber-500">
            Input
          </TabsTrigger>
          <TabsTrigger value="content" className="rounded-none data-[state=active]:border-b-2 data-[state=active]:border-amber-500">
            Content
          </TabsTrigger>
          <TabsTrigger value="logic" className="rounded-none data-[state=active]:border-b-2 data-[state=active]:border-amber-500">
            Logic
          </TabsTrigger>
          <TabsTrigger value="media" className="rounded-none data-[state=active]:border-b-2 data-[state=active]:border-amber-500">
            Media
          </TabsTrigger>
        </TabsList>

        <ScrollArea className="flex-1">
          <TabsContent value="input" className="p-4 space-y-2 mt-0">
            {inputBlocks.map(renderToolboxItem)}
          </TabsContent>

          <TabsContent value="content" className="p-4 space-y-2 mt-0">
            {contentBlocks.map(renderToolboxItem)}
          </TabsContent>

          <TabsContent value="logic" className="p-4 space-y-2 mt-0">
            {logicBlocks.map(renderToolboxItem)}
          </TabsContent>

          <TabsContent value="media" className="p-4 space-y-2 mt-0">
            {mediaBlocks.map(renderToolboxItem)}
          </TabsContent>
        </ScrollArea>
      </Tabs>
    </div>
  );
};

// src/lib/components/Toolbox.svelte
<script lang="ts">
	import { BlockType } from '$lib/types';
	import {
		Type,
		AlignLeft,
		Minus,
		Image as ImageIcon,
		Settings,
		List,
		CheckSquare,
		Calendar,
		FileSignature,
		Hash,
		Mail,
		CircleDot,
		UploadCloud,
		FileText,
		Calculator,
		CreditCard,
		Video,
		DollarSign
	} from 'lucide-svelte';
	import { cn } from '$lib/utils';

	interface ToolboxProps {
		onDragStart: (e: DragEvent, type: BlockType) => void;
		onAddBlock: (type: BlockType) => void;
	}

	let { onDragStart, onAddBlock }: ToolboxProps = $props();

	// Colors for categories - enhanced for dark mode
	const CATEGORY_COLORS = {
		primitive:
			'bg-zinc-100 border-zinc-300 hover:bg-zinc-200 dark:bg-zinc-900 dark:border-zinc-700 dark:hover:bg-zinc-800',
		input:
			'bg-blue-50 border-blue-200 hover:bg-blue-100 dark:bg-blue-900/20 dark:border-blue-800 dark:hover:bg-blue-900/40',
		smart:
			'bg-purple-50 border-purple-200 hover:bg-purple-100 dark:bg-purple-900/20 dark:border-purple-800 dark:hover:bg-purple-900/40',
		media:
			'bg-amber-50 border-amber-200 hover:bg-amber-100 dark:bg-amber-900/20 dark:border-amber-800 dark:hover:bg-amber-900/40',
		logic:
			'bg-rose-50 border-rose-200 hover:bg-rose-100 dark:bg-rose-900/20 dark:border-rose-800 dark:hover:bg-rose-900/40',
		layout:
			'bg-indigo-50 border-indigo-200 hover:bg-indigo-100 dark:bg-indigo-900/20 dark:border-indigo-800 dark:hover:bg-indigo-900/40'
	};
</script>

{#snippet toolItem(type: BlockType, Icon: any, label: string, colorClass: string)}
	<div
		draggable="true"
		ondragstart={(e) => onDragStart(e, type)}
		onclick={() => onAddBlock(type)}
		role="button"
		tabindex="0"
		onkeydown={(e) => e.key === 'Enter' && onAddBlock(type)}
		class={cn(
			'group relative flex cursor-grab items-center gap-3 overflow-hidden border-2 p-2.5 transition-all active:cursor-grabbing hover:-translate-y-[2px] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[2px_2px_0px_0px_rgba(255,255,255,0.2)]',
			colorClass,
			'border-black dark:border-zinc-600'
		)}
	>
		<Icon
			class="relative z-10 h-4 w-4 text-black opacity-70 transition-none group-hover:opacity-100 dark:text-zinc-100"
		/>
		<span
			class="relative z-10 font-mono text-[11px] font-bold uppercase leading-none tracking-wider text-black dark:text-zinc-100"
			>{label}</span
		>
	</div>
{/snippet}

{#snippet sectionHeader(title: string, number: string)}
	<div
		class="mb-3 mt-2 flex w-full items-center justify-between border-b-2 border-black pb-2 dark:border-zinc-700"
	>
		<span
			class="font-mono text-[10px] font-black uppercase tracking-widest text-foreground dark:text-white"
		>
			{title}
		</span>
		<span
			class="border-2 border-black bg-white px-1.5 font-mono text-[9px] font-bold text-black opacity-50 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white"
		>
			{number}
		</span>
	</div>
{/snippet}

<div class="flex-1 space-y-8 overflow-y-auto bg-white p-5 dark:bg-zinc-950">
	<!-- ESSENTIALS -->
	<div>
		{@render sectionHeader('Primitives', '01')}
		<div class="grid grid-cols-1 gap-2">
			{@render toolItem(BlockType.TEXT, Type, 'Text Block', CATEGORY_COLORS.primitive)}
			{@render toolItem(BlockType.INPUT, FileText, 'Short Answer', CATEGORY_COLORS.primitive)}
			{@render toolItem(BlockType.LONG_TEXT, AlignLeft, 'Paragraph', CATEGORY_COLORS.primitive)}
		</div>
	</div>

	<!-- DATA COLLECTION -->
	<div>
		{@render sectionHeader('Inputs', '02')}
		<div class="grid grid-cols-1 gap-2">
			<div class="grid grid-cols-2 gap-2">
				{@render toolItem(BlockType.CHECKBOX, CheckSquare, 'Check', CATEGORY_COLORS.input)}
				{@render toolItem(BlockType.RADIO, CircleDot, 'Radio', CATEGORY_COLORS.input)}
			</div>
			{@render toolItem(BlockType.SELECT, List, 'Dropdown Select', CATEGORY_COLORS.input)}
			{@render toolItem(BlockType.DATE, Calendar, 'Date Picker', CATEGORY_COLORS.input)}
			{@render toolItem(BlockType.EMAIL, Mail, 'Email Address', CATEGORY_COLORS.input)}
			{@render toolItem(BlockType.NUMBER, Hash, 'Number Input', CATEGORY_COLORS.input)}
		</div>
	</div>

	<!-- SMART BLOCKS -->
	<div>
		{@render sectionHeader('Smart Mods', '03')}
		<div class="grid grid-cols-1 gap-2">
			{@render toolItem(BlockType.FORMULA, Calculator, 'Calc / Formula', CATEGORY_COLORS.smart)}
			{@render toolItem(BlockType.PAYMENT, CreditCard, 'Payment Gateway', CATEGORY_COLORS.smart)}
			{@render toolItem(BlockType.CURRENCY, DollarSign, 'Currency Convert', CATEGORY_COLORS.smart)}
		</div>
	</div>

	<!-- MEDIA & FILES -->
	<div>
		{@render sectionHeader('Assets', '04')}
		<div class="grid grid-cols-1 gap-2">
			{@render toolItem(BlockType.SIGNATURE, FileSignature, 'E-Signature', CATEGORY_COLORS.media)}
			{@render toolItem(BlockType.FILE_UPLOAD, UploadCloud, 'File Upload', CATEGORY_COLORS.media)}
			<div class="grid grid-cols-2 gap-2">
				{@render toolItem(BlockType.IMAGE, ImageIcon, 'Img', CATEGORY_COLORS.media)}
				{@render toolItem(BlockType.VIDEO, Video, 'Vid', CATEGORY_COLORS.media)}
			</div>
			{@render toolItem(BlockType.SECTION_BREAK, Minus, 'Divider Line', CATEGORY_COLORS.media)}
		</div>
	</div>

	<!-- ADVANCED -->
	<div>
		{@render sectionHeader('Logic', '05')}
		<div class="space-y-2">
			{@render toolItem(BlockType.CONDITIONAL, Settings, 'Conditional Branch', CATEGORY_COLORS.logic)}
			{@render toolItem(BlockType.REPEATER, List, 'Repeater Group', CATEGORY_COLORS.logic)}
		</div>
	</div>
</div>
